PLACES = [
    {"place": "Mohenjo-daro", "era": "Indus Valley Civilization (c. 2500 BCE)"},
    {"place": "Dholavira", "era": "Indus Valley Civilization (c. 2500 BCE)"},
    {"place": "Hastinapur", "era": "Late Vedic Period (c. 900 BCE)"},
    {"place": "Rajgir", "era": "Mahajanapadas (c. 500 BCE)"},
    {"place": "Taxila", "era": "Maurya Empire (c. 250 BCE)"},
    {"place": "Patna", "era": "Maurya Empire (c. 250 BCE)"},
    {"place": "Ujjain", "era": "Gupta Empire (c. 400 CE)"},
    {"place": "Nalanda", "era": "Gupta Empire (c. 500 CE)"},
    {"place": "Mahabalipuram", "era": "Pallava Dynasty (c. 700 CE)"},
    {"place": "Badami", "era": "Chalukya Dynasty (c. 600 CE)"},
    {"place": "Ellora", "era": "Rashtrakuta Dynasty (c. 800 CE)"},
    {"place": "Thanjavur", "era": "Chola Empire (c. 1000 CE)"},
    {"place": "Madurai", "era": "Pandya Kingdom (c. 1300 CE)"},
    {"place": "Belur", "era": "Hoysala Empire (c. 1150 CE)"},
    {"place": "Warangal", "era": "Kakatiya Dynasty (c. 1250 CE)"},
    {"place": "Hampi", "era": "Vijayanagara Empire (c. 1500 CE)"},
    {"place": "Delhi", "era": "Delhi Sultanate (c. 1350 CE)"},
    {"place": "Fatehpur Sikri", "era": "Mughal Empire (c. 1575 CE)"},
    {"place": "Agra", "era": "Mughal Empire (c. 1650 CE)"},
    {"place": "Pune", "era": "Maratha Empire (c. 1750 CE)"},
    {"place": "Srirangapatna", "era": "Kingdom of Mysore (c. 1790 CE)"},
    {"place": "Amritsar", "era": "Sikh Empire (c. 1830 CE)"},
    {"place": "Kolkata", "era": "British East India Company (c. 1820 CE)"},
    {"place": "Shimla", "era": "British Raj (c. 1900 CE)"},
    {"place": "Delhi", "era": "Indian Independence (1947)"}
]
